steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/interview-ai',
        '--build-arg', 'DATABASE_URL=${DATABASE_URL}',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/interview-ai'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
